export const USER_REPOSITORY = 'USER_REPOSITORY';
export const COMPANY_REPOSITORY = 'COMPANY_REPOSITORY';
export const FARM_REPOSITORY = 'FARM_REPOSITORY';
export const PLANT_REPOSITORY = 'PLANT_REPOSITORY';
export const DEVICE_REPOSITORY = 'DEVICE_REPOSITORY';
export const SENSOR_REPOSITORY = 'SENSOR_REPOSITORY';
export const MEASURING_HISTORY_REPOSITORY = 'MEASURING_HISTORY_REPOSITORY';
export const GALERY_PLANTS_COMMENTS_REPOSITORY =
  'GALERY_PLANTS_COMMENTS_REPOSITORY';
export const GALERY_PLANTS_LIKES_REPOSITORY = 'GALERY_PLANTS_LIKES_REPOSITORY';

export const SEQUELIZE = 'SEQUELIZE';
