export const jwtConstants = {
  secret:
    'REVTQVJST0xMQURPIFBPUiBDUkhJU1RJQU4gREFWSUQgVkVSR0FSQSBHT01FWiwgQ0VMICs1NzMxODM5MTkxODcsIE1BSUw6IEtSSVNTS0lSQUBHTUFJTC5DT00=',
};

export enum GROUPS {
  ADMIN = 'ADMIN',
  BASIC = 'BASIC',
}
